# Generated by Django 3.2.16 on 2022-12-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('logo', models.TextField(max_length=250)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
