# Generated by Django 3.2.16 on 2022-12-21 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('photo', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=20)),
                ('employee_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies_api.companies')),
            ],
        ),
    ]
