# Generated by Django 3.2.16 on 2022-12-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_api', '0006_alter_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
